spring:
  application:
    name: levelup

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: 'classpath:changeLog.xml'

server:
  port: 8080
  servlet:
    context-path: /catalog
levelup:
  application:
    useStorage: false
